[package]
name = "mgallery"
version = "0.3.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rusqlite = "0.26.1"
image = "0.23.14"
img_hash = "3.2.0"
lazy_static = "1.4.0"
